"""corridas de ingesta

Revision ID: 1c4890b9ae49
Revises: 31f6a0733615
Create Date: 2026-07-27 19:55:08.288358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4890b9ae49'
down_revision: Union[str, Sequence[str], None] = '31f6a0733615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridas_ingesta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(), nullable=False),
    sa.Column('terminada_en', sa.DateTime(), nullable=True),
    sa.Column('fuentes_ok', sa.Integer(), nullable=False),
    sa.Column('fuentes_con_error', sa.Integer(), nullable=False),
    sa.Column('avisos_encontrados', sa.Integer(), nullable=False),
    sa.Column('avisos_nuevos', sa.Integer(), nullable=False),
    sa.Column('avisos_cerrados', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corridas_ingesta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corridas_ingesta_iniciada_en'), ['iniciada_en'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corridas_ingesta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corridas_ingesta_iniciada_en'))

    op.drop_table('corridas_ingesta')
    # ### end Alembic commands ###
