"""esquema inicial

Revision ID: 31f6a0733615
Revises: 
Create Date: 2026-07-27 15:39:33.315250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f6a0733615'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_gmail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre_remitente', sa.String(length=200), nullable=True),
    sa.Column('firma', sa.Text(), nullable=True),
    sa.Column('refresh_token_cifrado', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_token_expira', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('conectada_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cuentas_gmail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cuentas_gmail_email'), ['email'], unique=True)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=True),
    sa.Column('nombre_normalizado', sa.String(length=200), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('industria', sa.String(length=120), nullable=True),
    sa.Column('dotacion_estimada', sa.Integer(), nullable=True),
    sa.Column('sitio_web', sa.String(length=300), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('tiene_equipo_ta', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dominio')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_industria'), ['industria'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_nombre_normalizado'), ['nombre_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_pais'), ['pais'], unique=False)

    op.create_table('perfil_consultora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=300), nullable=True),
    sa.Column('email_contacto', sa.String(length=200), nullable=True),
    sa.Column('industrias_objetivo', sa.Text(), nullable=False),
    sa.Column('paises_objetivo', sa.Text(), nullable=False),
    sa.Column('dotacion_min', sa.Integer(), nullable=False),
    sa.Column('dotacion_max', sa.Integer(), nullable=False),
    sa.Column('seniorities_objetivo', sa.Text(), nullable=False),
    sa.Column('fee_promedio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=400), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_ingreso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=60), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('es_decisor', sa.Boolean(), nullable=False),
    sa.Column('fuente_url', sa.String(length=600), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contactos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('NUEVO', 'CONTACTADO', 'EN_CONVERSACION', 'REUNION', 'PROPUESTA', 'GANADO', 'PERDIDO', name='estadolead'), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_urgencia', sa.Float(), nullable=False),
    sa.Column('score_fit', sa.Float(), nullable=False),
    sa.Column('score_accesibilidad', sa.Float(), nullable=False),
    sa.Column('score_pago', sa.Float(), nullable=False),
    sa.Column('razones', sa.Text(), nullable=False),
    sa.Column('gancho', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=120), nullable=True),
    sa.Column('proximo_paso', sa.String(length=300), nullable=True),
    sa.Column('motivo_perdida', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('ultimo_contacto_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_empresa_id'), ['empresa_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_leads_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_score'), ['score'], unique=False)

    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('rol_normalizado', sa.String(length=200), nullable=False),
    sa.Column('seniority', sa.Enum('JUNIOR', 'SEMI_SENIOR', 'SENIOR', 'JEFATURA', 'DIRECCION', 'INDEFINIDO', name='seniority'), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=2), nullable=True),
    sa.Column('modalidad', sa.String(length=40), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=60), nullable=False),
    sa.Column('fuente_url', sa.String(length=600), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.Column('primera_vez_vista', sa.Date(), nullable=False),
    sa.Column('ultima_vez_vista', sa.Date(), nullable=False),
    sa.Column('cerrada', sa.Boolean(), nullable=False),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('reposteos', sa.Integer(), nullable=False),
    sa.Column('publicada_por_consultora', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'external_id', name='uq_vacante_fuente_externa')
    )
    with op.batch_alter_table('vacantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vacantes_cerrada'), ['cerrada'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacantes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacantes_fuente'), ['fuente'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacantes_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_vacantes_rol_normalizado'), ['rol_normalizado'], unique=False)

    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('autor', sa.String(length=120), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividades_lead_id'), ['lead_id'], unique=False)

    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.Enum('SALIENTE', 'ENTRANTE', name='direccion'), nullable=False),
    sa.Column('para', sa.String(length=300), nullable=False),
    sa.Column('de', sa.String(length=300), nullable=True),
    sa.Column('asunto', sa.String(length=400), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('plantilla', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ENVIADO', 'ERROR', 'RECIBIDO', name='estadomensaje'), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=120), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=120), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuentas_gmail.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensajes_direccion'), ['direccion'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensajes_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensajes_lead_id'))
        batch_op.drop_index(batch_op.f('ix_mensajes_estado'))
        batch_op.drop_index(batch_op.f('ix_mensajes_direccion'))

    op.drop_table('mensajes')
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actividades_lead_id'))

    op.drop_table('actividades')
    with op.batch_alter_table('vacantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vacantes_rol_normalizado'))
        batch_op.drop_index(batch_op.f('ix_vacantes_pais'))
        batch_op.drop_index(batch_op.f('ix_vacantes_fuente'))
        batch_op.drop_index(batch_op.f('ix_vacantes_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_vacantes_cerrada'))

    op.drop_table('vacantes')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_score'))
        batch_op.drop_index(batch_op.f('ix_leads_estado'))
        batch_op.drop_index(batch_op.f('ix_leads_empresa_id'))

    op.drop_table('leads')
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contactos_empresa_id'))

    op.drop_table('contactos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('perfil_consultora')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_pais'))
        batch_op.drop_index(batch_op.f('ix_empresas_nombre_normalizado'))
        batch_op.drop_index(batch_op.f('ix_empresas_industria'))

    op.drop_table('empresas')
    with op.batch_alter_table('cuentas_gmail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cuentas_gmail_email'))

    op.drop_table('cuentas_gmail')
    # ### end Alembic commands ###
