"""objetivos y fuentes en la base

Revision ID: 54b556ab09b2
Revises: 1c4890b9ae49
Create Date: 2026-07-27 20:33:43.989720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b556ab09b2'
down_revision: Union[str, Sequence[str], None] = '1c4890b9ae49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=200), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('revisado_en', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('objetivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objetivos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_objetivos_nombre_normalizado'), ['nombre_normalizado'], unique=False)
        batch_op.create_index(batch_op.f('ix_objetivos_resultado'), ['resultado'], unique=False)

    op.create_table('fuentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('identificador', sa.String(length=600), nullable=False),
    sa.Column('empresa', sa.String(length=200), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=True),
    sa.Column('stealth', sa.Boolean(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.Column('ultima_corrida', sa.DateTime(), nullable=True),
    sa.Column('avisos_ultima_corrida', sa.Integer(), nullable=True),
    sa.Column('ultimo_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'identificador', name='uq_fuente_tipo_identificador')
    )
    with op.batch_alter_table('fuentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuentes_activa'), ['activa'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuentes_objetivo_id'), ['objetivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fuentes_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fuentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fuentes_tipo'))
        batch_op.drop_index(batch_op.f('ix_fuentes_objetivo_id'))
        batch_op.drop_index(batch_op.f('ix_fuentes_activa'))

    op.drop_table('fuentes')
    with op.batch_alter_table('objetivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objetivos_resultado'))
        batch_op.drop_index(batch_op.f('ix_objetivos_nombre_normalizado'))
        batch_op.drop_index(batch_op.f('ix_objetivos_activo'))

    op.drop_table('objetivos')
    # ### end Alembic commands ###
