"""fecha aproximada en vacantes

Revision ID: de4b46217fd8
Revises: 54b556ab09b2
Create Date: 2026-07-27 20:56:27.721035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de4b46217fd8'
down_revision: Union[str, Sequence[str], None] = '54b556ab09b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default es imprescindible: sin él, agregar una columna NOT NULL a
    # una tabla que ya tiene filas falla ("column contains null values") y el
    # deploy se cae contra la base de producción. Las vacantes existentes vienen
    # de fuentes con fecha exacta, así que False es el valor correcto para ellas.
    with op.batch_alter_table('vacantes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'fecha_aproximada',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacantes', schema=None) as batch_op:
        batch_op.drop_column('fecha_aproximada')

    # ### end Alembic commands ###
