"""eventos de financiamiento

Revision ID: f488e8886cb2
Revises: de4b46217fd8
Create Date: 2026-07-28 14:51:29.914126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f488e8886cb2'
down_revision: Union[str, Sequence[str], None] = 'de4b46217fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('FINANCIAMIENTO', 'EXPANSION', 'CONTRATACION', name='tipoevento'), nullable=False),
    sa.Column('titulo', sa.String(length=400), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('empresa_mencionada', sa.String(length=200), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_aproximada', sa.Boolean(), nullable=False),
    sa.Column('fuente', sa.String(length=60), nullable=False),
    sa.Column('fuente_url', sa.String(length=600), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('descartado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuente', 'external_id', name='uq_evento_fuente_externa')
    )
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eventos_confirmado'), ['confirmado'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_descartado'), ['descartado'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_fuente'), ['fuente'], unique=False)
        batch_op.create_index(batch_op.f('ix_eventos_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eventos_tipo'))
        batch_op.drop_index(batch_op.f('ix_eventos_fuente'))
        batch_op.drop_index(batch_op.f('ix_eventos_fecha'))
        batch_op.drop_index(batch_op.f('ix_eventos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_eventos_descartado'))
        batch_op.drop_index(batch_op.f('ix_eventos_confirmado'))

    op.drop_table('eventos')
    # ### end Alembic commands ###
